### ISSUE TITLE
Task list 

### ISSUE THREAD

**Issue by Godofnothing** [Godofnothing/optimal_transport_problem#1]
### Algorithmic part
---
- [X] Implement vanilla sinkhorn for `numpy`, `jax.numpy` 
- [x] Implement vanilla sinkhorn for `scipy.sparse`
- [x] Implement stabilized sinkhorn for `numpy`, `jax.numpy` 
- [x] Implement stabilized sinkhorn for `scipy.sparse`
- [x] Implement `epsilon` scaling policies

 ### Experimenting part
---
- [ ] Tests on generated data
- [ ] Tests on images
- [ ] Tests on text data
- [ ] Further ideas?
